spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/school}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always